# Generated by Django 2.1.2 on 2019-10-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
