# Generated by Django 2.1.2 on 2019-10-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='age',
        ),
    ]
